#!/usr/bin/env python3
"""Embed a binary file in a C/C++ header as an unsigned char array.

    convert.py resources/RedX.png -o build/generated/resources/RedX_png.h
    convert.py resources/RedX.png -d build/generated/resources

The array is named after the input file with every character that is not
valid in a C identifier replaced by '_' (RedX.png -> RedX_png), matching
CMake's string(MAKE_C_IDENTIFIER). Only the standard library is used, so the
build can run this without a virtualenv or Pillow.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BYTES_PER_LINE = 16


def c_identifier(name: str) -> str:
    """Return `name` with every non-identifier character replaced by '_'."""
    ident = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if ident[0].isdigit():
        ident = "_" + ident
    return ident


def render_header(name: str, data: bytes, source: str) -> str:
    """Return the header text for array `name` holding `data`."""
    guard = f"EMBEDDED_{name.upper()}_H"
    lines = [
        f"// Generated by scripts/convert.py from {source}; do not edit.",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"static const unsigned char {name}[] = {{",
    ]
    for offset in range(0, len(data), BYTES_PER_LINE):
        chunk = data[offset : offset + BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += ["};", "", f"#endif  // {guard}", ""]
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("input", type=Path, help="binary file to embed")
    parser.add_argument(
        "--name", help="array name (default: derived from the input file name)"
    )
    where = parser.add_mutually_exclusive_group()
    where.add_argument("-o", "--output", type=Path, help="header to write")
    where.add_argument(
        "-d",
        "--out-dir",
        type=Path,
        help="directory to write <name>.h into (default: next to the input)",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    name = args.name or c_identifier(args.input.name)
    output: Path = args.output or (args.out_dir or args.input.parent) / f"{name}.h"

    try:
        data = args.input.read_bytes()
    except OSError as exc:
        print(f"convert.py: cannot read {args.input}: {exc}", file=sys.stderr)
        return 1
    if not data:
        print(f"convert.py: {args.input} is empty", file=sys.stderr)
        return 1

    try:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(render_header(name, data, args.input.name))
    except OSError as exc:
        print(f"convert.py: cannot write {output}: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
